export type ProjectLink = {
  kind: "github" | "figma" | "demo" | "case_study" | "other";
  url: string;
  label?: string;
};

export type Project = {
  id: string;
  title: string;
  kind?: string;
  year?: string;
  summary: string;
  what_it_does: string;
  role: string;
  role_detail?: string;
  tools: string[];
  outcomes?: string[];
  links?: ProjectLink[];
  /**
   * Optional path to a screenshot. Drop a file into /public/images/ and set
   * `image: "/images/your-screenshot.png"`. Until then the card uses a
   * generated placeholder so the layout still feels finished.
   */
  image?: string;
  /**
   * Whether this project is shown publicly on the site. Defaults to true if
   * omitted. Set to false to keep an entry in this file (so the content isn't
   * lost) without rendering its card.
   */
  published?: boolean;
};

/**
 * Add new projects by appending objects to this array.
 * No JSX or component changes needed — the UI consumes this list directly.
 */
export const projects: Project[] = [
  {
    id: "eeg-stroke",
    // Hidden from the public site for now. Flip `published` to true (or remove the
    // field) when you're ready to publicize this work. All copy below is still
    // placeholder from the initial scaffold and needs to be rewritten with your
    // real account before publishing.
    published: false,
    title: "Portable EEG Cap — EMT Stroke Triage",
    kind: "Clinical UI/UX",
    year: "TODO",
    summary:
      "TODO: rewrite — placeholder summary generated during scaffolding.",
    what_it_does:
      "TODO: rewrite — placeholder description generated during scaffolding. The original autogenerated copy was inaccurate and is not your real account of this project.",
    role: "TODO",
    role_detail:
      "TODO: rewrite with your actual role on this project.",
    tools: [],
    outcomes: [],
    links: [],
  },
  {
    id: "it-request-form",
    title: "GoCloud ServiceDesk",
    kind: "Internal Tool",
    year: "2026 — Present",
    summary:
      "Onboarding, offboarding, and change-request management system — a web-based platform for IT user lifecycle workflows, with state-driven UI and automated backend integrations.",
    what_it_does:
      "Replaces disconnected, manual request flows with a single web-based interface for managing user onboarding, offboarding, and change requests across IT and operations. State-driven UI logic adapts the form based on request type, surfacing only the relevant fields. Back-end integrations automate the downstream actions through a Spring Boot service, the project database, and the Microsoft Graph API. Built to support both day-to-day operations and product validation milestones — including investor presentations at GoCloud.",
    role: "UX/UI Designer & Front-End Developer",
    role_detail:
      "UX/UI Designer & Front-End Developer at GoCloud Inc. Led interface design and front-end implementation: translated complex IT operations requirements into a coherent, state-driven UI; collaborated with the back-end developer and lead software engineer on integration with the Spring Boot service, the database, and Microsoft Graph API; and refined the experience iteratively using Docker, npm, and Claude Code. Currently extending the system with AI-enhanced features to automate and scale lifecycle workflows.",
    tools: [
      "Figma",
      "HTML",
      "CSS",
      "JavaScript",
      "Microsoft Graph API",
      "Docker",
      "npm",
      "Claude Code",
    ],
    // Outcomes intentionally empty — better blank than fabricated. Add real
    // metrics here when you can verify them, e.g.:
    //   "Replaced three disconnected legacy request paths with one form"
    //   "Used in live investor presentations and product validation"
    outcomes: [],
    // TODO: add real links once you decide what to publish (Figma file,
    // case-study writeup, demo video, internal wiki page, etc.).
    links: [],
    image: "/images/gocloud-servicedesk.png",
  },
];
